Repository SC-ECE/ML-PROJECT, pull requests merged in 2023-01, with the labels that each got.

#1 Stock Price Prediction using Machine Learning in Python
  stock_prediction.ipynb
Labels: Easy, Synapse

#3 SMS Spam Classifier
  SMS Spam Classifier/Readme.md
  SMS Spam Classifier/detector.ipynb
  SMS Spam Classifier/model.pkl
  SMS Spam Classifier/spam.csv
Labels: Medium, Synapse

#5 Sales Prediction
  Sales Prediction/Advertising.csv
  Sales Prediction/Readme.md
  Sales Prediction/Sales_Prediction.ipynb
  Sales Prediction/sales.pkl
Labels: Medium, Synapse

#6 Handwritten Digit Recognizer
  Handwritten-Digit-Recognizer/Readme.md
  Handwritten-Digit-Recognizer/digit_recognizer.ipynb
  Handwritten-Digit-Recognizer/mnist.h5
Labels: Hard, Synapse

#10 House Price Predictions
  House Price Predictions/House Price Predictions.ipynb
  House Price Predictions/HousePricePrediction.joblib
  House Price Predictions/Housing.csv
  House Price Predictions/Model Outputs
  House Price Predictions/README.md
  House Price Predictions/housing.data
  House Price Predictions/housing.names
Labels: Medium, Synapse

#8 Iris Flowers Classification
  Iris Flowers Classification/Readme.md
  Iris Flowers Classification/classify.ipynb
  Iris Flowers Classification/iris.csv
  Iris Flowers Classification/iris_flower.pkl
Labels: Medium, Synapse

#9 Profit prediction
  Profit of an item/clustering/Readme.md
  Profit of an item/clustering/Sample.xlsx
  Profit of an item/clustering/clusturing.ipynb
  Profit of an item/clustering/demo1.txt
Labels: Medium, Synapse

#12 Age & Gender detection From Images
  Age & Gender Detection From Image/Readme.md
  Age & Gender Detection From Image/agegender-predictor.ipynb
Labels: Hard, Synapse

#13 Money Authentication & Decision Tree Visulaization
  Money Authentication & Decision Tree Visulaization/Readme.md
  Money Authentication & Decision Tree Visulaization/authenticator.ipynb
  Money Authentication & Decision Tree Visulaization/bank_notes.csv
Labels: Hard, Synapse

#14 Google Stock Price Prediction
  Google Stock Price Prediction/Google Stock Price Prediction.ipynb
  Google Stock Price Prediction/Google_test_data.csv
  Google Stock Price Prediction/Google_train_data.csv
  Google Stock Price Prediction/Readme.md
Labels: Medium, Synapse

#15 Credit Card Approval Prediction
  Credit Card Approval Prediction/Credit Card Approval Prediction.ipynb
  Credit Card Approval Prediction/Data/credit_approval.data
  Credit Card Approval Prediction/Readme.md
Labels: Medium, Synapse

#16 bit coin predictor
  bit coin pred/BTC_INR_Historical Data.csv
  bit coin pred/Bit coin.ipynb
  bit coin pred/readme.md
Labels: Medium, Synapse

#17 Gold Rate Prediction
  Gold_Rate_Prediction/Gold_Price_Prediction.ipynb
  Gold_Rate_Prediction/Readme.md
  Gold_Rate_Prediction/gld_price_data.csv
Labels: Medium, Synapse

#18 Wine Quality Prediction
  Wine Quality Prediction/Readme.md
  Wine Quality Prediction/Wine_Quality_Pred.ipynb
  Wine Quality Prediction/winequality.csv
Labels: Medium, Synapse

#19 Stock Market Prediction And Forecasting Using Stacked LSTM
  Stock Market Prediction And Forecasting Using Stacked LSTM/NSE-TATAGLOBAL.csv
  Stock Market Prediction And Forecasting Using Stacked LSTM/Readme.md
  Stock Market Prediction And Forecasting Using Stacked LSTM/stock_prediction.ipynb
Labels: Medium, Synapse

#21 Item buying prediction with respect to age
  Item buying prediction with respect to age/logistic_regression.ipynb
  Item buying prediction with respect to age/readme.md
Labels: Hard, Synapse

#20 Diabetes Prediction
  Diabetes Prediction/Readme.md
  Diabetes Prediction/diabetes.csv
  Diabetes Prediction/diabetes_prediction.ipynb
Labels: Medium, Synapse

#22 Fake News Prediction
  Fake News Prediction/Fake News Prediction.ipynb
  Fake News Prediction/Readme.md
Labels: Medium, Synapse

#24 Traffic Sign Detector
  Traffic Sign Detector/Readme.md
  Traffic Sign Detector/traffic.ipynb
Labels: Medium, Synapse

#25 DNA Classification
  DNA Classification/DNA Sequences.ipynb
  DNA Classification/Readme.md
Labels: Medium, Synapse
